### ISSUE TITLE
Footer component shows two times

### ISSUE THREAD

**Issue by santosh-gaggle** [scandipwa/base-theme#1009]
**Description**:
Footer is showing two times. it should be one time
**Expected behavior**:
 it should show one time

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/56184739/93847428-8302a680-fcc4-11ea-8d30-dd90932c793c.png)

**To Reproduce**:
only home page include it two times and the other pages it's look ok

**Versions**:
Magento 2.3.5-p2
scandipwa 3.1

**Comment by santosh-gaggle** [comment]
Hello @drc0 ,
if we removed the footer component form src/app/route/HomePage/HomePage.container.js
then  I think the footer will not show on mobile so we can't remove it.

in the mobile view, you will find that the footer component is rendering in the homepage component 
and in the desktop view, you will find that the footer is rendering in a separate component.

**Comment by drc0** [comment]
@santosh-gaggle you are right, but I argue the footer should always be visible:

Preamble:
- I get now that the choice for mobile was to hide the footer because of the sticky nav bar on bottom, and place the footer only on homepage, your pull #1325 follows this choice

Comment:
- I think the footer should always be visible in every page also on mobile because people often put there privacy and contact informations, privacy policies are to be available in every page for legal reasons, and in an ecommerce having contacts and support page link handy in the footer is often preferred.

I think the solution should let the footer be always visible also removing duplication of concerns among components/containers by rendering the footer from two places altogether.

**Comment by yeegor** [comment]
Hi! 
The initial issue has been fixed in #1325, nevertheless I see that @drc0 has some points that I agree with. 
Let's keep this issue as a feature request, thank you for your contribution! 🚀

**Comment by alfredsgenkins** [comment]
We decided not to show footer on every page, as this leads to confusion on my-account, checkout, PLP (with infinite scroll). So it stays on mobile on homepage only for now.

We plan on redesigning footer in the future. Every project changes it, we should provide more common default solution.
