### ISSUE TITLE
Add native push notification support

### ISSUE THREAD

**Issue by atachh** [scandipwa/base-theme#106]
**Is your feature request related to a problem? Please describe.**
Implement native push notifications in supported browsers

**Describe the solution you'd like**
1) Use native notifications whenever possible and use regular as a fallback for non-supported browsers
2) Make event listeners for "window.focus" and "window.blur" to make it flexible
3) Use handlers for different incomes, such as when user grants or denies the permission to show notifications in browser
4) Make a connection between service worker and Magento backend to allow notifications to be send even if the website is currently closed

**Comment by alfredsgenkins** [comment]
This idea was dropped. We might get back to it later, but I am closing this for now.

**Comment by devselegento** [comment]
Since ScandiPWA is on version 3 and more developers start using the theme, I would like to ask if there is any progress in supporting push notifications.

Using InjectManifest of workbox, the sw can be extended to support push notifications plus the process is straight forward following the [docs](https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications)
