### ISSUE TITLE
Can't display menu if there are missing cms blocks in other requests

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#135]
**Describe the bug**
After creating new project without sample data and adding menu manually in BE it is not displayed on FE due missing cms blocks that are not related to menu itself.

**To Reproduce**
1. Start new project without sample data
2. Create new menu in admin
3. Menu throws error, but it is present in graphql response

**Expected behavior**
Menu is displayed even if some cms blocks are missing, since they are not related in any way. I did not test what happens if you have some blocks and some are missing, but this could be a problem if page breaks when some cms block is removed from admin and not from the FE. Default behavior should be to show error in console or toast and display what can be displayed.

**Screenshots**
https://imgur.com/a/LQMI7tO

**Comment by alfredsgenkins** [comment]
First of all, there is only one request for CMS blocks, slider and menu. Not caching any responses containing errors is intentional. If there are any errors in request, the request should not be cached by server at all. Frontend acts the same, SW is not saving the response in cache, etc. We are treating the response containing errors very consistently throughout the application. We won't fix this issue.
