### ISSUE TITLE
Free shipping rule doesn't work

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/base-theme#1691]
**Description**:
Free shipping rule doesn't work

**Expected behavior**:
Rule works -> free shipping is displayed

**To Reproduce**:
1. Open Admin panel -> go to Marketing > Promotions > Cart Price Rules
2. Tap 'Add new rule'
3. Enter Add mandatory fields (name, website, Customer Groups and etc)
4. Select 'No coupon' in the Coupon field
5. Set 'Yes' in Apply to Shipping Amount
6. Select 'For shipment with matching items' in the Free Shipping field
7. Tap 'Save' -> clear cash
8. Open website -> Add products to the cart -> open cart page
9. Go to shipping step

**Actual result**:
Free shipping is missing 

**Notes:**
Rule in the Admin panel: https://scandipwapmrev.indvp.com/admin/sales_rule/promo_quote/edit/id/3/key/9a130202e6f8d34c274face29e5ba3e1f58c630936d8576bd07b1312020eda5c/

**Comment by zans-laksa** [comment]
Found this documentation pages:
* [Price rules setup](https://docs.magento.com/user-guide/marketing/price-rules-cart-free-shipping.html)
* [Free shipping setup](https://docs.magento.com/user-guide/shipping/shipping-free.html)

They says, that in order to setup cart price rules for free shipping, we should enable "free shipping" delivery method and set minimal amount to the very high value.
In that case free shipping will be triggered only by a price rule.

I've tried this on my local setup and it works both on luma and scandipwa theme.

Cart price rule disabled
![image](https://user-images.githubusercontent.com/73945186/99946233-b0300b80-2d7e-11eb-9880-a08dfa749b39.png)

Cart price rule enabled
![image](https://user-images.githubusercontent.com/73945186/99946308-d2298e00-2d7e-11eb-9738-23e80fb31af7.png)
