### ISSUE TITLE
Discrepancies in product display functionality 

### ISSUE THREAD

**Issue by kandrejevs** [scandipwa/base-theme#197]
**Describe the bug**
I have compared product and category display functionality against default 2.3.1 magento.

1. for PWA disabled category is still visible on FE, in default magento it is not.
2. in product page, when product visibility is set to catalog only, product is out of stock and magento do not display out of stock products, in default store product is visible by directly visiting URL, in PWA it is not visible.
3. in product page when product visibility is search only, product is in stock or out of stock and magento displays or does not display out of stock products default magento shows product by directly opening URL, PWA does not.
4. in PDP when product visibility is catalog and search and when it is out of stock and magento does not display out of stock products, in default magento product is visible by directly opening URL, in PWA it is not visible

![image](https://user-images.githubusercontent.com/4084128/60100477-7c544f00-9762-11e9-9299-0ca6be9136a0.png)

**Expected behavior**
Consistent behavior to default magento functionality

**Comment by eli-l** [comment]
1. PWA is using Menu organizer (menu manager) which is not the same as category, so disabling category have no impact on menu content.
2. Fixed in scandipwa/catalog-graphql:1.4.2 - product is visible by direct URL
3. Fixed in scandipwa/catalog-graphql:1.4.2 - product is visible by direct URL
4. Fixed in scandipwa/catalog-graphql:1.4.2 - product is visible by direct URL
