### ISSUE TITLE
Add to cart button breaks on PLP

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#229]
**Describe the bug**
When a simple product is added to cart from PLP, the `ADD TO CART` button does not stop loading even though the product has been already added. 

**To Reproduce**
1. Go to PLP 
2. Add a simple product to cart from the PLP
3. **Notice the button loading** 

**Expected behavior**
After a product is added to cart, the `ADD TO CART` button should stop loading.

**Comment by malikahmed1996** [comment]
@lianastaskevica on category page the add to cart component is placed at:
`vendor/scandipwa/source/src/app/component/AddToCart/AddToCart.component.js`
The product is added but the button is stuck because it tries to remove the the specific item from wishlist array at Line:54
```
        // for configurable products productToBeRemovedAfterAdd will be saved in state
        if (removeWishlistItem || (productToBeRemovedAfterAdd === sku && wishlistItems[id])) {
            const product = wishlistItems[id];

            removeProductFromWishlist({ product, noMessages: true });
        }
```

as removeWishlistItem is boolean operator which is in your case is true and wishlistItems[id] doesn't exist you are getting the error
 
```
Wishlist.query.js:39 Uncaught (in promise) TypeError: Cannot read property 'item_id' of undefined
    at Wishlist.getRemoveProductFromWishlistMutation (Wishlist.query.js:39)
    at WishlistDispatcher.removeItemFromWishlist (Wishlist.dispatcher.js:81)
    at removeProductFromWishlist (AddToCart.container.js:24)
    at AddToCart.afterAdded (AddToCart.component.js:58)
    at AddToCart.component.js:109
```
you can just replace the if condition with and operator (&&) instead of or operator (||)

`if (removeWishlistItem && productToBeRemovedAfterAdd === sku && wishlistItems[id])`

<b>so it only executes the only if `removeWishlistItem` is TRUE and `productToBeRemovedAfterAdd === sku` is TRUE and specific item is in `wishlistItems` array</b>
