### ISSUE TITLE
Tax & price calculation, tax breakdown needs improvement

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/base-theme#675]
**Bug description**:
"Catalog Prices" setting does not work in admin->stores->comfigurations->sales->tax->calculation settings. 

**Steps to reproduce**:
1. Open any product on storefront and add it to cart (make sure he has tax amount when added to cart)
2. Notice the tax amount
3. Open admin->stores->comfigurations->sales->tax->calculation settings. 
4. Set "catalog prices" to "including tax"
5. open FE
6. Add same product to cart
7. notice nothing change in tax calculation

**Expected result**:
The total price is the same you see as a product price on PDP 

**Additional information**:
Please sync to Hadi and Janis to ask what fixes he has, perhaps there are more bugs regarding taxes.

**Comment by ejnshtein** [comment]
Works as intended on ScandiPWA 3.1.2

Catalog Prices is set to "Including Tax", tax is included in the product price.
![Screenshot_20201002_142047](https://user-images.githubusercontent.com/18352350/94918113-911da780-04ba-11eb-82e9-97c2357bd3af.png)

Catalog Prices is set to "Excluding Tax", tax is excluded in the product price, and added to the order total.
![Screenshot_20201002_142300](https://user-images.githubusercontent.com/18352350/94918213-c75b2700-04ba-11eb-9069-522668365769.png)

If you see that tax is 0$ that may be because the product "Tax Class" is set to "None".
![Screenshot_20201002_142648](https://user-images.githubusercontent.com/18352350/94918470-4f413100-04bb-11eb-9109-65ab542849a6.png)

After setting "Tax Class" to "Taxable Goods" tax is calculated
![Screenshot_20201002_142830](https://user-images.githubusercontent.com/18352350/94918630-9cbd9e00-04bb-11eb-8b75-ff8d1125e0eb.png)
 properly.
