### ISSUE TITLE
.IsMobile() unsupported.

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/base-theme#716]
**Description**:
.IsMobile() is going to be unsupported from google mid september.

**Screenshots, Video, Logs**
https://www.zdnet.com/article/google-to-phase-out-user-agent-strings-in-chrome/

**Comment by ejnshtein** [comment]
This shouldn't be a problem, since they are **freezing** user agent string, not removing or anything.
And current codebase requires only device type, not browser & OS version.

**Comment by ejnshtein** [comment]
<img width="691" alt="Screenshot 2020-07-16 at 21 58 25" src="https://user-images.githubusercontent.com/18352350/87711284-bcdc9b80-c7af-11ea-9eeb-3352914481a9.png">
As was mentioned in [this](https://medium.com/@galmeiri/get-ready-for-chrome-user-agent-string-phase-out-c6840da1c31e) article, the only info that will be left in UA string is browser type (chrome, safari, e.t.c.) and device type (mobile, desktop).
So it will be required to change code that detects device type (mobile, tablet, desktop, android, ios, e.t.c.) without UA string using [Client Hints](https://wicg.github.io/ua-client-hints/).

**Comment by ejnshtein** [comment]
Using Clients Hints it will be enough to for mobile device and browser type, but our code also use different UI for tablets, so I see there three possible options:
1. Remove tablet specific code and replace it with mobile version.
2. Replace current UA-based code with device & platform detection via JavaScript APIs (can be unstable, since we'd use JS hacks).
3. Make render asynchronous and wait until promise with device information (platform and its version) will resolve and only after that render the whole app.

I think that tablet version can be easily replaced with mobile version, it should look fine on the tablet. (so, first option)
Also, Safari on iPad enables desktop version [by default](https://support.apple.com/en-gb/guide/ipad/ipad999d68f9/ipados#iPadfd466c35/), other browsers have desktop mode button in quick settings.
