### ISSUE TITLE
Allowing to Enter the Search Page for No inputs

### ISSUE THREAD

**Issue by ankith-codilar** [scandipwa/base-theme#729]
**Description**:
In Search Bar when there is input provided message is given as **Start typing to see search results!** but when the **ENTER** character is entered it redirects to Search Page which is 404! if entering search page without any result redirects to 404 then it doesn't make sense allowing it

**Expected behavior**:
Allowing Enter only after the input is provided

**Screenshots, Video, Logs**

![screenshot-demo scandipwa com-2020 07 13-12_02_14](https://user-images.githubusercontent.com/67680823/87278885-30a64c00-c503-11ea-947a-d35bae974374.png)

![screenshot-demo scandipwa com-2020 07 13-12_02_14 (1)](https://user-images.githubusercontent.com/67680823/87278900-40be2b80-c503-11ea-833a-94419c4edeb4.png)

**To Reproduce**:
1. Go to Search Bar
2. Click **ENTER** character 
3. Redirects to 404

**Comment by ejnshtein** [comment]
There's also a search results preview, so changing only `onSearchEnterPress` method won't work because user will still see suggestions without result, that's why I added in `handleChange` trimming for user input. Also, with regexp like `/\s\s+/g` it will actually replace every second space symbol, that's why I used regexp `/^\s+/` to trim only spaces from the start.
I guess we can also add trimmer for the string end 🤔
