### ISSUE TITLE
Migrate to webpack-dev-server proxy

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/base-theme#786]
**Description**:
Wepack-dev-server proxy must be used, instead of complex Nginx configs. This would allow easier M2 existing setup.

**Expected behavior**:
What did you expect to happen?

**Additional context**:

This can be used instead:

```js
proxy: [{
    context: ['/graphql', '/static', '/media', '/pub'],
    target: 'https://pwademo.dk.magento2x2.scandesigns.dk/',
    changeOrigin: true
}]
```

**Comment by astik** [comment]
I was thinking the same thing today =)
It would be great to have this directly in the build tool, making it easier to setup for remote development.
Also, it would be great to have a nice environment variable to define the target.
For example, the system could do :
- if a PROXY_TARGET env variable is defined, use this variable to configure proxy target
- else, if a "proxy" property is defined in package.json, use this property to configure proxy target
- else, by default no proxy is handled by webpack-dev-server, leaving the possibility to do it at upper level (with nginx like what is done currently for example)

This chain of fallback is what is used in create-react-app: https://create-react-app.dev/docs/proxying-api-requests-in-development/

In create-react-app, they also allow the definition of proxySetup.js in order to configure directly the app and add custom middleware (https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually).

**Comment by alfredsgenkins** [comment]
I am think the same. Probably, we will drop the idea of composer-based theme modules. And migrate to completelly node module based approach. The fallback to core theme will also be done as node_module, so no more need for composer or vendor. It is good the V3 was in beta the whole time, now now can focus on create-react-app based approach and deliver a setup doable in 10 minutes without any complications.

I am thinking about BE development as well, there we should decrease inconsistency, currently the development environment resource-requirements are too high, we MUST focus on minimizing this values.

And thanks for links, I will share the architecutre proposal later next week @astik

**Comment by alfredsgenkins** [comment]
I am also thinking of hiding webpack configurations, just like in react-app, but still allowing to override them. I am thinking to minimize the overhead and technology exposed to devs, theoretically giving them an ability to override / modify configs.

I am also thinking to migrate the VSCode extension for plugin / override creation into a separate module, so it's AST based override / parsing can be used via the API, and the VSCode, CLI can implement it for GUI. Then, we can have automatic extension via the CLI, VSCode and any IDE desired.

**Comment by alfredsgenkins** [comment]
I closed this by mistake :D
