### ISSUE TITLE
White Page shows if there is product in cart that is not available anymore

### ISSUE THREAD

**Issue by lion152** [scandipwa/base-theme#973]
**Description**:

Currently, there is an issue that ScandiPWA does not have a handler for a case where the client has a product in the cart but that product becomes unavailable.

**Expected behavior**:

There is no WHITE page on the site in cases when the customer has a product in cart that is not available anymore.

**Additional context**:
The solution can be found here:https://github.com/scandipwacloud/pwacloud-manzara-qrz-1592288542/pull/17/commits/e9a90f4d3fb751bffe26d1aa8bebec15d0fa7c66

**Comment by ejnshtein** [comment]
The solution provided in manazara repo is not exactly fix for this issue.
They've done that if a product added to the cart is out of stock they just remove it from the user cart. This is not correct behavior.

Expected behavior:
User adds a product to cart.
The product becomes out of stock.
The product is marked **out of stock** in the cart and shouldn't be counted in final price.
In checkout may also display message **Some products are out of stock. To proceed checkout please remove them from cart.** or something like that.
